In [167]:
import pandas as pd

In [168]:
df = pd.read_csv("globalAirQuality.csv")

In [169]:
print(df,type(df))

                        timestamp country      city  latitude  longitude  \
0      2025-11-04 18:25:17.554219      US  New York    40.713    -74.006
1      2025-11-04 19:25:17.554219      US  New York    40.713    -74.006
2      2025-11-04 20:25:17.554219      US  New York    40.713    -74.006
3      2025-11-04 21:25:17.554219      US  New York    40.713    -74.006
4      2025-11-04 22:25:17.554219      US  New York    40.713    -74.006
...                           ...     ...       ...       ...        ...
17995  2025-11-19 13:25:17.554219      CH    Zurich    47.377      8.542
17996  2025-11-19 14:25:17.554219      CH    Zurich    47.377      8.542
17997  2025-11-19 15:25:17.554219      CH    Zurich    47.377      8.542
17998  2025-11-19 16:25:17.554219      CH    Zurich    47.377      8.542
17999  2025-11-19 17:25:17.554219      CH    Zurich    47.377      8.542

         pm25     pm10     no2    so2      o3     co  aqi  temperature  \
0      50.295  108.938  27.998  6.539  52.568  1.096  108       18.504
1      32.083   63.043  36.120  4.021  43.536  1.075   90        5.838
2      42.250   82.553  26.935  9.538  23.320  0.977   84       31.833
3      30.403   79.951  63.536  7.609  31.369  0.230  158       23.140
4      21.083   66.423  38.997  6.919  45.615  1.085   97       13.632
...       ...      ...     ...    ...     ...    ...  ...          ...
17995  27.899   74.179  41.474  6.677  50.869  1.028  103        7.079
17996   2.950   47.988  42.235  2.821  35.551  0.644  105       28.734
17997  61.347   72.908  46.976  5.763  66.492  0.947  122       21.951
17998  40.722   95.152  32.957  5.524  53.193  0.868   95       24.042
17999  25.830   30.411  35.317  4.336  66.246  0.848   88        8.529

       humidity  wind_speed
0        70.168       3.725
1        80.088       8.969
2        62.783       9.650
3        89.153       8.956
4        76.499       4.017
...         ...         ...
17995    52.443       7.452
17996    85.678       4.496
17997    72.311       9.660
17998    31.880       2.642
17999    59.104       4.403

[18000 rows x 15 columns] <class 'pandas.core.frame.DataFrame'>

In [170]:
df.head()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017

In [171]:
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [172]:
df["country"]

0        US
1        US
2        US
3        US
4        US
         ..
17995    CH
17996    CH
17997    CH
17998    CH
17999    CH
Name: country, Length: 18000, dtype: object

In [173]:
df["city"]

0        New York
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object

In [174]:
df[["city","aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [175]:
df[["city","aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [176]:
#accessing rows

df.loc[0]

timestamp      2025-11-04 18:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                               50.295
pm10                              108.938
no2                                27.998
so2                                 6.539
o3                                 52.568
co                                  1.096
aqi                                   108
temperature                        18.504
humidity                           70.168
wind_speed                          3.725
Name: 0, dtype: object

In [177]:
df.loc[0:2]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650

In [178]:
df.iloc[2]

timestamp      2025-11-04 20:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                                42.25
pm10                               82.553
no2                                26.935
so2                                 9.538
o3                                  23.32
co                                  0.977
aqi                                    84
temperature                        31.833
humidity                           62.783
wind_speed                           9.65
Name: 2, dtype: object

In [179]:
df.iloc[0:2]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969

In [180]:
df.loc[0,"aqi"]
df.index
df.columns

Index(['timestamp', 'country', 'city', 'latitude', 'longitude', 'pm25', 'pm10',
       'no2', 'so2', 'o3', 'co', 'aqi', 'temperature', 'humidity',
       'wind_speed'],
      dtype='object')

In [181]:
df.loc[0:2,"city"]
df.iloc[0:2,2]

0    New York
1    New York
Name: city, dtype: object

In [182]:
df.loc[0:2,["country","city","latitude","longitude"]]

  country      city  latitude  longitude
0      US  New York    40.713    -74.006
1      US  New York    40.713    -74.006
2      US  New York    40.713    -74.006

In [183]:
df.iloc[0:3,1:5]

  country      city  latitude  longitude
0      US  New York    40.713    -74.006
1      US  New York    40.713    -74.006
2      US  New York    40.713    -74.006

In [184]:
df.at[0,"city"]

'New York'

In [185]:
df.iat[0,2]

'New York'

In [186]:
# filtering the data....

df[df["aqi"]>100]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
8,2025-11-05 02:25:17.554219,US,New York,40.713,-74.006,60.914,44.775,40.936,6.779,36.751,1.014,121,24.092,48.148,8.686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787
17993,2025-11-19 11:25:17.554219,CH,Zurich,47.377,8.542,76.613,37.495,29.662,5.419,57.042,1.103,153,20.437,79.602,2.663
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660

In [187]:
df[ (df["aqi"]>100) & (df["temperature"]>30) ]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
14,2025-11-05 08:25:17.554219,US,New York,40.713,-74.006,38.815,121.394,25.969,4.112,44.730,1.124,121,34.481,81.790,3.576
17,2025-11-05 11:25:17.554219,US,New York,40.713,-74.006,63.552,57.838,13.754,4.427,42.251,0.997,127,36.193,62.906,7.097
25,2025-11-05 19:25:17.554219,US,New York,40.713,-74.006,56.954,75.045,29.837,9.541,54.198,1.170,113,31.289,43.279,5.264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17947,2025-11-17 13:25:17.554219,CH,Zurich,47.377,8.542,53.938,75.183,16.255,7.263,67.244,0.457,107,32.584,81.544,7.101
17950,2025-11-17 16:25:17.554219,CH,Zurich,47.377,8.542,70.255,60.620,32.081,2.065,47.803,0.852,140,36.885,34.173,1.748
17975,2025-11-18 17:25:17.554219,CH,Zurich,47.377,8.542,33.406,98.160,44.654,0.807,45.160,0.737,111,30.761,76.073,3.570
17976,2025-11-18 18:25:17.554219,CH,Zurich,47.377,8.542,73.493,89.558,9.313,4.768,51.505,0.745,146,30.909,81.573,1.024
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787

In [188]:
aqi_data = df[df["aqi"]>100][["city","aqi"]]
aqi_data
aqi_data.iloc[0]
aqi_data.loc[6]

city    New York
aqi          155
Name: 6, dtype: object

In [189]:
# filtering using query methos...

df.query("aqi > 100 & temperature > 30")[["city","aqi"]]

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [190]:
aqi_val = 100
df.query("aqi > @aqi_val & temperature > 30")[["city","aqi"]]
aqi_data = df.query("aqi > @aqi_val & temperature > 30")[["city","aqi"]].copy()

In [191]:
aqi_data

           city  aqi
6      New York  155
7      New York  115
14     New York  121
17     New York  127
25     New York  113
...         ...  ...
17947    Zurich  107
17950    Zurich  140
17975    Zurich  111
17976    Zurich  146
17991    Zurich  104

[2384 rows x 2 columns]

In [192]:
#cleaning data...
raw_datas = pd.DataFrame({
    "Employee_ID": [101, 102, 103, 102, 104, 105, 105],
    "Name": ["Amit", "Riya", None, "Riya", "Suresh", "Neha", "Neha"],
    "Age": [25, 30, 28, 30, None, 27, 27],
    "Salary": [50000, 60000, None, 60000, 55000, 52000, 52000]
})

print(raw_datas)
raw_datas.to_csv("raw_datas",index=False)

   Employee_ID    Name   Age   Salary
0          101    Amit  25.0  50000.0
1          102    Riya  30.0  60000.0
2          103    None  28.0      NaN
3          102    Riya  30.0  60000.0
4          104  Suresh   NaN  55000.0
5          105    Neha  27.0  52000.0
6          105    Neha  27.0  52000.0

In [193]:
#handle missing values...
df = pd.read_csv("raw_datas")

In [194]:
df.isnull()
df.isna()

   Employee_ID   Name    Age  Salary
0        False  False  False   False
1        False  False  False   False
2        False   True  False    True
3        False  False  False   False
4        False  False   True   False
5        False  False  False   False
6        False  False  False   False

In [195]:
 df

   Employee_ID    Name   Age   Salary
0          101    Amit  25.0  50000.0
1          102    Riya  30.0  60000.0
2          103     NaN  28.0      NaN
3          102    Riya  30.0  60000.0
4          104  Suresh   NaN  55000.0
5          105    Neha  27.0  52000.0
6          105    Neha  27.0  52000.0

In [196]:
df.isnull().sum()

Employee_ID    0
Name           1
Age            1
Salary         1
dtype: int64

In [197]:
df.dropna()

   Employee_ID  Name   Age   Salary
0          101  Amit  25.0  50000.0
1          102  Riya  30.0  60000.0
3          102  Riya  30.0  60000.0
5          105  Neha  27.0  52000.0
6          105  Neha  27.0  52000.0

In [198]:
df.dropna(axis=1)

   Employee_ID
0          101
1          102
2          103
3          102
4          104
5          105
6          105

In [199]:
df.fillna(0)

   Employee_ID    Name   Age   Salary
0          101    Amit  25.0  50000.0
1          102    Riya  30.0  60000.0
2          103       0  28.0      0.0
3          102    Riya  30.0  60000.0
4          104  Suresh   0.0  55000.0
5          105    Neha  27.0  52000.0
6          105    Neha  27.0  52000.0

In [200]:
df.fillna(0)

   Employee_ID    Name   Age   Salary
0          101    Amit  25.0  50000.0
1          102    Riya  30.0  60000.0
2          103       0  28.0      0.0
3          102    Riya  30.0  60000.0
4          104  Suresh   0.0  55000.0
5          105    Neha  27.0  52000.0
6          105    Neha  27.0  52000.0

In [201]:
cleaned_data = df.copy()

In [202]:
cleaned_data["Age"] = cleaned_data["Age"].fillna(age_mean)

In [203]:
age_mean = df["Age"].mean()

In [204]:
cleaned_data

   Employee_ID    Name        Age   Salary
0          101    Amit  25.000000  50000.0
1          102    Riya  30.000000  60000.0
2          103     NaN  28.000000      NaN
3          102    Riya  30.000000  60000.0
4          104  Suresh  27.833333  55000.0
5          105    Neha  27.000000  52000.0
6          105    Neha  27.000000  52000.0

In [205]:
cleaned_data

   Employee_ID    Name        Age   Salary
0          101    Amit  25.000000  50000.0
1          102    Riya  30.000000  60000.0
2          103     NaN  28.000000      NaN
3          102    Riya  30.000000  60000.0
4          104  Suresh  27.833333  55000.0
5          105    Neha  27.000000  52000.0
6          105    Neha  27.000000  52000.0

In [206]:
df

   Employee_ID    Name   Age   Salary
0          101    Amit  25.0  50000.0
1          102    Riya  30.0  60000.0
2          103     NaN  28.0      NaN
3          102    Riya  30.0  60000.0
4          104  Suresh   NaN  55000.0
5          105    Neha  27.0  52000.0
6          105    Neha  27.0  52000.0

In [207]:
df.bfill()

   Employee_ID    Name   Age   Salary
0          101    Amit  25.0  50000.0
1          102    Riya  30.0  60000.0
2          103    Riya  28.0  60000.0
3          102    Riya  30.0  60000.0
4          104  Suresh  27.0  55000.0
5          105    Neha  27.0  52000.0
6          105    Neha  27.0  52000.0

In [208]:
df.ffill()

   Employee_ID    Name   Age   Salary
0          101    Amit  25.0  50000.0
1          102    Riya  30.0  60000.0
2          103    Riya  28.0  60000.0
3          102    Riya  30.0  60000.0
4          104  Suresh  30.0  55000.0
5          105    Neha  27.0  52000.0
6          105    Neha  27.0  52000.0

In [209]:
#handle duplicate values....

df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
dtype: bool

In [210]:
df[["Name"]].duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
dtype: bool

In [211]:
df[["Name","Age"]].duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
dtype: bool

In [212]:
df.drop_duplicates()

   Employee_ID    Name   Age   Salary
0          101    Amit  25.0  50000.0
1          102    Riya  30.0  60000.0
2          103     NaN  28.0      NaN
4          104  Suresh   NaN  55000.0
5          105    Neha  27.0  52000.0

In [213]:
df2 = df.copy()
df2

   Employee_ID    Name   Age   Salary
0          101    Amit  25.0  50000.0
1          102    Riya  30.0  60000.0
2          103     NaN  28.0      NaN
3          102    Riya  30.0  60000.0
4          104  Suresh   NaN  55000.0
5          105    Neha  27.0  52000.0
6          105    Neha  27.0  52000.0

In [214]:
df.drop_duplicates(inplace = True)

In [215]:
df

   Employee_ID    Name   Age   Salary
0          101    Amit  25.0  50000.0
1          102    Riya  30.0  60000.0
2          103     NaN  28.0      NaN
4          104  Suresh   NaN  55000.0
5          105    Neha  27.0  52000.0

##

In [216]:
df2

   Employee_ID    Name   Age   Salary
0          101    Amit  25.0  50000.0
1          102    Riya  30.0  60000.0
2          103     NaN  28.0      NaN
3          102    Riya  30.0  60000.0
4          104  Suresh   NaN  55000.0
5          105    Neha  27.0  52000.0
6          105    Neha  27.0  52000.0

In [217]:
df = df2

In [218]:
#handle Data  Types and date-time....

df.dtypes

Employee_ID      int64
Name            object
Age            float64
Salary         float64
dtype: object

In [219]:
df2 = df.copy()
df2 = df2.fillna(0)
df2 = df2["Age"].astype("int64").copy()
df2.dtypes

dtype('int64')

In [220]:
df2

0    25
1    30
2    28
3    30
4     0
5    27
6    27
Name: Age, dtype: int64

In [221]:
aqi_data = pd.read_csv("globalAirQuality.csv")

In [222]:
aqi_data

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [223]:
date_str = pd.Series([pd.to_datetime("2026-12-31")])
type(date_str.dtypes)

numpy.dtypes.DateTime64DType

In [224]:
#handle strings.....

df["Name"].str.lower()

0      amit
1      riya
2       NaN
3      riya
4    suresh
5      neha
6      neha
Name: Name, dtype: object

In [225]:
df["Name"].str.upper()

0      AMIT
1      RIYA
2       NaN
3      RIYA
4    SURESH
5      NEHA
6      NEHA
Name: Name, dtype: object

In [226]:
df["Name"].str.capitalize()

0      Amit
1      Riya
2       NaN
3      Riya
4    Suresh
5      Neha
6      Neha
Name: Name, dtype: object

In [227]:
df["Name"].str.split("i")

0     [Am, t]
1     [R, ya]
2         NaN
3     [R, ya]
4    [Suresh]
5      [Neha]
6      [Neha]
Name: Name, dtype: object

In [228]:
df["Name"].str.contains("neha",case=False)

0    False
1    False
2      NaN
3    False
4    False
5     True
6     True
Name: Name, dtype: object

In [229]:
df2 = df.copy()

df2

In [230]:
df2

   Employee_ID    Name   Age   Salary
0          101    Amit  25.0  50000.0
1          102    Riya  30.0  60000.0
2          103     NaN  28.0      NaN
3          102    Riya  30.0  60000.0
4          104  Suresh   NaN  55000.0
5          105    Neha  27.0  52000.0
6          105    Neha  27.0  52000.0

In [231]:
##Feature engineering...

df2["tax"] = df2["Salary"].apply(lambda x : "20%" if x <= 50000 else "10%")
df2
df2["Gender"] = df2["Name"].apply(lambda x : "Female" if (x == "Riya" or x == "Neha") else "Male" )

In [235]:
# map funcion....
gender_map = {"Male" : "M", "Female" : "F"}
df2["Gender"] = df2["Gender"].map(gender_map)

# assign function....

df2 = df2.assign(newSalary = df2["Salary"] * 1.1)

In [236]:
#replace function...

df2["tax"] = df2["tax"].replace("10%","15%")

In [237]:
df2

   Employee_ID    Name   Age   Salary  tax Gender  newSalary
0          101    Amit  25.0  50000.0  20%    NaN    55000.0
1          102    Riya  30.0  60000.0  15%    NaN    66000.0
2          103     NaN  28.0      NaN  15%    NaN        NaN
3          102    Riya  30.0  60000.0  15%    NaN    66000.0
4          104  Suresh   NaN  55000.0  15%    NaN    60500.0
5          105    Neha  27.0  52000.0  15%    NaN    57200.0
6          105    Neha  27.0  52000.0  15%    NaN    57200.0

In [238]:
df2

   Employee_ID    Name   Age   Salary  tax Gender  newSalary
0          101    Amit  25.0  50000.0  20%    NaN    55000.0
1          102    Riya  30.0  60000.0  15%    NaN    66000.0
2          103     NaN  28.0      NaN  15%    NaN        NaN
3          102    Riya  30.0  60000.0  15%    NaN    66000.0
4          104  Suresh   NaN  55000.0  15%    NaN    60500.0
5          105    Neha  27.0  52000.0  15%    NaN    57200.0
6          105    Neha  27.0  52000.0  15%    NaN    57200.0

In [239]:
df2

   Employee_ID    Name   Age   Salary  tax Gender  newSalary
0          101    Amit  25.0  50000.0  20%    NaN    55000.0
1          102    Riya  30.0  60000.0  15%    NaN    66000.0
2          103     NaN  28.0      NaN  15%    NaN        NaN
3          102    Riya  30.0  60000.0  15%    NaN    66000.0
4          104  Suresh   NaN  55000.0  15%    NaN    60500.0
5          105    Neha  27.0  52000.0  15%    NaN    57200.0
6          105    Neha  27.0  52000.0  15%    NaN    57200.0

In [266]:
df2.columns = ["id","name","age","salary","tax","gender","new_salary"]

In [267]:
df2

    id    name   age   salary  tax gender  new_salary
0  101    Amit  25.0  50000.0  20%    NaN     55000.0
1  102    Riya  30.0  60000.0  15%    NaN     66000.0
2  103     NaN  28.0      NaN  15%    NaN         NaN
3  102    Riya  30.0  60000.0  15%    NaN     66000.0
4  104  Suresh   NaN  55000.0  15%    NaN     60500.0
5  105    Neha  27.0  52000.0  15%    NaN     57200.0
6  105    Neha  27.0  52000.0  15%    NaN     57200.0

In [268]:
df2.rename(columns={"salary":"income"})

    id    name   age   income  tax gender  new_salary
0  101    Amit  25.0  50000.0  20%    NaN     55000.0
1  102    Riya  30.0  60000.0  15%    NaN     66000.0
2  103     NaN  28.0      NaN  15%    NaN         NaN
3  102    Riya  30.0  60000.0  15%    NaN     66000.0
4  104  Suresh   NaN  55000.0  15%    NaN     60500.0
5  105    Neha  27.0  52000.0  15%    NaN     57200.0
6  105    Neha  27.0  52000.0  15%    NaN     57200.0

In [269]:
df2.rename(index={1:"first"})

        id    name   age   salary  tax gender  new_salary
0      101    Amit  25.0  50000.0  20%    NaN     55000.0
first  102    Riya  30.0  60000.0  15%    NaN     66000.0
2      103     NaN  28.0      NaN  15%    NaN         NaN
3      102    Riya  30.0  60000.0  15%    NaN     66000.0
4      104  Suresh   NaN  55000.0  15%    NaN     60500.0
5      105    Neha  27.0  52000.0  15%    NaN     57200.0
6      105    Neha  27.0  52000.0  15%    NaN     57200.0

In [270]:
#sort by value...

df2.sort_values("salary")

    id    name   age   salary  tax gender  new_salary
0  101    Amit  25.0  50000.0  20%    NaN     55000.0
5  105    Neha  27.0  52000.0  15%    NaN     57200.0
6  105    Neha  27.0  52000.0  15%    NaN     57200.0
4  104  Suresh   NaN  55000.0  15%    NaN     60500.0
1  102    Riya  30.0  60000.0  15%    NaN     66000.0
3  102    Riya  30.0  60000.0  15%    NaN     66000.0
2  103     NaN  28.0      NaN  15%    NaN         NaN

In [271]:
df2.sort_values("salary",ascending=False)

    id    name   age   salary  tax gender  new_salary
1  102    Riya  30.0  60000.0  15%    NaN     66000.0
3  102    Riya  30.0  60000.0  15%    NaN     66000.0
4  104  Suresh   NaN  55000.0  15%    NaN     60500.0
5  105    Neha  27.0  52000.0  15%    NaN     57200.0
6  105    Neha  27.0  52000.0  15%    NaN     57200.0
0  101    Amit  25.0  50000.0  20%    NaN     55000.0
2  103     NaN  28.0      NaN  15%    NaN         NaN

In [272]:
sorted_df = df2.sort_values(["salary","age"])
sorted_df

    id    name   age   salary  tax gender  new_salary
0  101    Amit  25.0  50000.0  20%    NaN     55000.0
5  105    Neha  27.0  52000.0  15%    NaN     57200.0
6  105    Neha  27.0  52000.0  15%    NaN     57200.0
4  104  Suresh   NaN  55000.0  15%    NaN     60500.0
1  102    Riya  30.0  60000.0  15%    NaN     66000.0
3  102    Riya  30.0  60000.0  15%    NaN     66000.0
2  103     NaN  28.0      NaN  15%    NaN         NaN

In [273]:
sorted_df.sort_index()

    id    name   age   salary  tax gender  new_salary
0  101    Amit  25.0  50000.0  20%    NaN     55000.0
1  102    Riya  30.0  60000.0  15%    NaN     66000.0
2  103     NaN  28.0      NaN  15%    NaN         NaN
3  102    Riya  30.0  60000.0  15%    NaN     66000.0
4  104  Suresh   NaN  55000.0  15%    NaN     60500.0
5  105    Neha  27.0  52000.0  15%    NaN     57200.0
6  105    Neha  27.0  52000.0  15%    NaN     57200.0

In [274]:
sorted_df

    id    name   age   salary  tax gender  new_salary
0  101    Amit  25.0  50000.0  20%    NaN     55000.0
5  105    Neha  27.0  52000.0  15%    NaN     57200.0
6  105    Neha  27.0  52000.0  15%    NaN     57200.0
4  104  Suresh   NaN  55000.0  15%    NaN     60500.0
1  102    Riya  30.0  60000.0  15%    NaN     66000.0
3  102    Riya  30.0  60000.0  15%    NaN     66000.0
2  103     NaN  28.0      NaN  15%    NaN         NaN

In [275]:
sorted_df.reset_index()
sorted_df.reset_index(drop=True)

    id    name   age   salary  tax gender  new_salary
0  101    Amit  25.0  50000.0  20%    NaN     55000.0
1  105    Neha  27.0  52000.0  15%    NaN     57200.0
2  105    Neha  27.0  52000.0  15%    NaN     57200.0
3  104  Suresh   NaN  55000.0  15%    NaN     60500.0
4  102    Riya  30.0  60000.0  15%    NaN     66000.0
5  102    Riya  30.0  60000.0  15%    NaN     66000.0
6  103     NaN  28.0      NaN  15%    NaN         NaN

In [277]:
sorted_df["ranking"] = sorted_df["salary"].rank(ascending=False,method="dense")
sorted_df

    id    name   age   salary  tax gender  new_salary  ranking
0  101    Amit  25.0  50000.0  20%    NaN     55000.0      4.0
5  105    Neha  27.0  52000.0  15%    NaN     57200.0      3.0
6  105    Neha  27.0  52000.0  15%    NaN     57200.0      3.0
4  104  Suresh   NaN  55000.0  15%    NaN     60500.0      2.0
1  102    Riya  30.0  60000.0  15%    NaN     66000.0      1.0
3  102    Riya  30.0  60000.0  15%    NaN     66000.0      1.0
2  103     NaN  28.0      NaN  15%    NaN         NaN      NaN

In [278]:
df3 = df2.copy()

In [280]:
#shifting a column.....

new_col_order = [col for  col in df3.columns if col != "id"]+["id"]
print(new_col_order)
df3[new_col_order]

['name', 'age', 'salary', 'tax', 'gender', 'new_salary', 'id']

     name   age   salary  tax gender  new_salary   id
0    Amit  25.0  50000.0  20%    NaN     55000.0  101
1    Riya  30.0  60000.0  15%    NaN     66000.0  102
2     NaN  28.0      NaN  15%    NaN         NaN  103
3    Riya  30.0  60000.0  15%    NaN     66000.0  102
4  Suresh   NaN  55000.0  15%    NaN     60500.0  104
5    Neha  27.0  52000.0  15%    NaN     57200.0  105
6    Neha  27.0  52000.0  15%    NaN     57200.0  105